name: ML Model CI

on:
  push:
    branches-ignore:
      - "main"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Configure DVC Credentials
        run: |
          dvc remote modify origin --local access_key_id ${{ secrets.DAGSHUB_TOKEN }}
          dvc remote modify origin --local secret_access_key ${{ secrets.DAGSHUB_TOKEN }}

      - name: Pull Data (DVC)
        run: dvc pull -r origin

      - name: Train and Log MLflow
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI}}
          MLFLOW_TRACKING_USERNAME: 17-doha 
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: python -m app.main

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-info
          path: model_info.txt

  